using UnityEngine;

namespace TaskbarHero
{
    /// <summary>
    /// The shared pixel-art look: a dark-fantasy palette (charcoal iron-framed panels,
    /// crimson banners, gold/bronze accents) modeled on taskbar idle RPGs. The matching
    /// 9-slice panel/button sprites are PNGs generated by the editor art tool into
    /// Resources/TaskbarHero/UI, so the scene builder and runtime code share one look.
    /// </summary>
    public static class UiTheme
    {
        // Iron panel frame
        public static readonly Color32 Outline = Hex(0x17161A);
        public static readonly Color32 IronLight = Hex(0x6E6A78);
        public static readonly Color32 Iron = Hex(0x504D59);
        public static readonly Color32 IronDark = Hex(0x37343E);
        public static readonly Color32 PanelFill = Hex(0x232229);

        // Crimson banner
        public static readonly Color32 BannerEdge = Hex(0x4A1316);
        public static readonly Color32 BannerLight = Hex(0xA93A30);
        public static readonly Color32 Banner = Hex(0x8E2226);
        public static readonly Color32 BannerFill = Hex(0x7A1B20);

        // Bronze button
        public static readonly Color32 ButtonLight = Hex(0xA8763F);
        public static readonly Color32 Button = Hex(0x6F4520);
        public static readonly Color32 ButtonDark = Hex(0x482B12);
        public static readonly Color32 ButtonFill = Hex(0x7C4E24);

        // Gold coin / pill rim
        public static readonly Color32 PillEdge = Hex(0x1A1208);
        public static readonly Color32 PillRim = Hex(0xB98A34);
        public static readonly Color32 PillRimDark = Hex(0x96692A);
        public static readonly Color32 PillFill = Hex(0x17150F);
        public static readonly Color32 CoinEdge = Hex(0x7A5216);
        public static readonly Color32 Coin = Hex(0xF0B13E);
        public static readonly Color32 CoinLight = Hex(0xFFE18F);
        public static readonly Color32 CoinDark = Hex(0xC9882C);

        // Text
        public static readonly Color32 Gold = Hex(0xF2C14E);
        public static readonly Color32 Cream = Hex(0xF2E7D0);
        public static readonly Color32 CreamDim = Hex(0xB9B0A0);

        // Bars
        public static readonly Color32 HpGreen = Hex(0x58C24F);
        public static readonly Color32 HpRed = Hex(0xE04838);
        public static readonly Color32 BarBack = Hex(0x1C1B20);

        /// <summary>Boss/danger accent as a rich-text hex (matches <see cref="HpRed"/>).</summary>
        public const string BossHex = "#E04838";

        /// <summary>Rarity accent as a rich-text hex, for colored item names in the loot feed.</summary>
        public static string RarityHex(Rarity rarity) => rarity switch
        {
            Rarity.Epic => "#C173F0",
            Rarity.Rare => "#58A6F0",
            _ => "#C9C2B4",
        };

        static Color32 Hex(int rgb) =>
            new Color32((byte)(rgb >> 16), (byte)(rgb >> 8), (byte)rgb, 255);
    }
}
